M48
; DRILL file {KiCad (6.0.0)} date Sat Jan 15 23:49:16 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-01-15T23:49:16+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0429
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0433
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0630
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1024
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C0.1259
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T6C0.1260
%
G90
G05
T1
X7.9941Y-3.386
X7.9941Y-3.4659
X8.2941Y-3.426
T2
X6.4961Y-4.5625
T3
X5.5118Y-4.5625
T4
X5.5276Y-2.6708
X6.4803Y-2.6708
T5
X6.1695Y-5.324
X6.6195Y-5.324
T6
X5.2832Y-4.6246
X5.8832Y-2.6246
X6.9832Y-2.6246
X7.1832Y-4.6746
T0
M30
